
 const ITEMS = [
    {
        id : '1',
        name:'Pretty hat',
        frontShape: "flatBill",
        Closure: "velcore",
        material: "cotton",
        color: "black",
        size: "small",
        price: 20,
        mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    },
    {
        id : '2',
        name:'Pretty hat',
        frontShape: "flatBill",
        Closure: "snapback",
        material: "cotton",
        color: "blue",
        size: "large",
        price: 20,
        mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    },
    {
        id : '3',
        name:'Pretty hat',
        frontShape: "flatBill",
        Closure: "buckle",
        material: "cotton",
        color: "yellow",
        size: "medium",
        price: 20,
        mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    },
    {
        id : '4',
        name:'Pretty hat',
        frontShape: "unstructured",
        Closure: "fitit",
        material: "cotton",
        color: "gray",
        size: "xlarge",
        price: 20,
         mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    },
    {
        id : '5',
        name:'Pretty hat',
        frontShape: "slightly",
        Closure: "velcore",
        material: "cotton",
        color: "black",
        size: "small",
        price: 20,
         mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    },
    {
        id : '6',
        name:'Pretty hat',
        frontShape: "slightly",
        Closure: "snapback",
        material: "cotton",
        color: "blue",
        size: "large",
        price: 20,
        mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    },
    {
        id : '7',
        name:'Pretty hat',
        frontShape: "slightly",
        Closure: "buckle",
        material: "cotton",
        color: "yellow",
        size: "medium",
        price: 20,
        mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    },
    {
        id : '8',
        name:'Pretty hat',
        frontShape: "flatBill",
        Closure: "fitit",
        material: "cotton",
        color: "gray",
        size: "xlarge",
        price: 20,
        mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    },
    {
        id : '9',
        name:'Pretty hat',
        frontShape: "curved",
        Closure: "velcore",
        material: "cotton",
        color: "black",
        size: "small",
        price: 20,
        mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    },
    {
        id : '10',
        name:'Pretty hat',
        frontShape: "curved",
        Closure: "snapback",
        material: "cotton",
        color: "blue",
        size: "large",
        price: 20,
        mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    },
    {
        id : '11',
        name:'Pretty hat',
        frontShape: "curved",
        Closure: "buckle",
        material: "cotton",
        color: "yellow",
        size: "medium",
        price: 20,
        mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    },
    {
        id : '12',
        name:'Pretty hat',
        frontShape: "curved",
        Closure: "fitit",
        material: "cotton",
        color: "yellow",
        size: "medium", 
        price: 20,
        mainImage: 'imgs/5.jpg',
        babyImage1:'',
        babyImage2: '',
        babyImage3: '',
        babyImage4: ''
    }
]

export default ITEMS;